### PR TITLE
Implement lock strategies

### PR DESCRIPTION
**Pull request by mhuggins**
@kapost/core This is intended to address #12.  It needs some work, but looking for feedback on the general approach.

### CODE REVIEW

**Comment by mhuggins** [comment]
Updated to use atomic operations.

**Comment by brandonc** [comment]
Very nice design. I couldn't find any issue.

**Comment by brandonc** [comment]
:+1:

**Comment by pk-nb** [comment]
:+1: Very cool! Really great documentation too.

**Comment by mhuggins** [comment]
@paul @brandonc The last commit here now support a NOOP lock strategy.  I've also made it so that the user can pass a `lock: false` option to the `#subcribe` method in order to use this strategy.

**Comment by icebreaker** [comment]
I wonder how much is the overhead of the locking.

**Comment by mhuggins** [comment]
It's doing a single atomic request, so it shouldn't be bad as long as the connection is a short hop.

**Pull request merged**
