### PR TITLE
Fixed provisioner console output and removed Rails inflector

### PR DESCRIPTION
**Pull request by brandonc**

### CODE REVIEW

**Comment by mhuggins** [comment]
Does this mean that 3.0.0 is broken? Should we unpublished that version from rubygems?

**Comment by brandonc** [comment]
Minor bug with the inflector that has been there for the last 3 versions. The rewording just adds more clarity to what was created

**Comment by mhuggins** [comment]
Did the `pluralize` call break if you didn't have ActiveSupport installed?

**Comment by brandonc** [comment]
It would have

**Pull request merged**
